locales: ["ko", "en"]
locale: "ko"

backend:
  name: git-gateway
  branch: main   # 커밋 반영할 브랜치

media_folder: "/img" # 이미지 저장 위치
public_folder: "/img"

editor:
  preview: false

collections:
  - name: "기사"
    label: "기사"
    folder: "articles"
    create: true
    # 파일명을 slug 필드 값으로 지정
    slug: "{{fields.slug}}"
    fields:
      - label: "File name (slug)"
        name: "slug"
        widget: "string"
        hint: "영어 소문자와 숫자만 입력하세요 (공백/특수문자 불가)"
        pattern:
          - "^[a-z0-9]+$"
          - "영어 소문자와 숫자만 사용할 수 있어요."
        required: true

      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "sports"
    label: "스포츠"
    folder: "sports"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - label: "File name (slug)"
        name: "slug"
        widget: "string"
        hint: "영어 소문자와 숫자만 입력하세요 (공백/특수문자 불가)"
        pattern:
          - "^[a-z0-9]+$"
          - "영어 소문자와 숫자만 사용할 수 있어요."
        required: true

      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
