
name: Build JSON index

on:
  push:
    paths:
      - "articles/**/*.md"   # 이 경로의 md가 바뀔 때만 실행해요
  workflow_dispatch:        # 수동 실행도 가능해요

permissions:
  contents: write           # index.json을 커밋하려면 필요해요

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # git 로그(최신 커밋 시간) 사용을 위해 0이 좋아요

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate index.json
        run: node .github/scripts/build-index.js

      - name: Commit & Push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/index.json
            git commit -m "chore: update index.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
